import type { PosePresetId } from "../schema/poseSchema";

export interface PosePresetDefinition {
  id: PosePresetId;
  label: string;
  controls: Record<string, number>;
}

export const MANNEQUIN_POSE_PRESETS: PosePresetDefinition[] = [
  { id: "stand", label: "站立", controls: {} },
  {
    id: "t-pose",
    label: "T型",
    controls: {
      "leftShoulder.spread": -70,
      "rightShoulder.spread": 70,
      "leftShoulder.pitch": 15,
      "rightShoulder.pitch": 15,
      "leftElbow.bend": 10,
      "rightElbow.bend": 10,
    },
  },
  {
    id: "walk",
    label: "行走",
    controls: {
      "leftShoulder.pitch": 20,
      "rightShoulder.pitch": -20,
      "leftHip.pitch": -20,
      "rightHip.pitch": 20,
      "leftKnee.bend": 12,
      "rightKnee.bend": 4,
    },
  },
  {
    id: "run",
    label: "跑步",
    controls: {
      "leftShoulder.pitch": 42,
      "rightShoulder.pitch": -42,
      "leftHip.pitch": -35,
      "rightHip.pitch": 40,
      "leftKnee.bend": 28,
      "rightKnee.bend": 18,
    },
  },
  {
    id: "sit",
    label: "坐姿",
    controls: {
      "torso.pitch": -10,
      "leftHip.pitch": 80,
      "rightHip.pitch": 80,
      "leftKnee.bend": 90,
      "rightKnee.bend": 90,
    },
  },
  {
    id: "crouch",
    label: "蹲下",
    controls: {
      "body.offsetY": -0.43,
      "body.pitch": -26,
      "torso.pitch": -24,
      "head.pitch": 22,
      "leftHip.pitch": 92,
      "rightHip.pitch": 92,
      "leftKnee.bend": 112,
      "rightKnee.bend": 112,
      "leftShoulder.pitch": 52,
      "rightShoulder.pitch": 50,
      "leftShoulder.spread": -10,
      "rightShoulder.spread": 10,
      "leftElbow.bend": 80,
      "rightElbow.bend": 76,
    },
  },
  {
    id: "kneel-one",
    label: "单膝跪",
    controls: {
      "body.offsetY": -0.42,
      "body.pitch": -16,
      "torso.pitch": -10,
      "head.pitch": 12,
      "leftHip.pitch": 68,
      "leftKnee.bend": 86,
      "leftFoot.pitch": 20,
      "rightHip.pitch": -15,
      "rightKnee.bend": 80,
      "rightFoot.pitch": 60,
      "leftShoulder.pitch": 5,
      "leftShoulder.spread": 10,
      "leftShoulder.twist": -10,
      "leftElbow.bend": 30,
      "rightShoulder.pitch": -18,
      "rightShoulder.spread": 10,
      "rightElbow.bend": 18,
    },
  },
  {
    id: "kneel-two",
    label: "双膝跪",
    controls: {
      "body.offsetY": -0.4,
      "body.pitch": 2,
      "torso.pitch": 8,
      "head.pitch": -2,
      "leftShoulder.pitch": -10,
      "rightShoulder.pitch": -10,
      "leftShoulder.spread": -5,
      "rightShoulder.spread": 5,
      "leftElbow.bend": 8,
      "rightElbow.bend": 8,
      "leftHip.pitch": -8,
      "rightHip.pitch": -8,
      "leftKnee.bend": 126,
      "rightKnee.bend": 126,
      "leftFoot.pitch": -20,
      "rightFoot.pitch": -20,
    },
  },
  {
    id: "hands-on-hips",
    label: "叉腰",
    controls: {
      "leftShoulder.pitch": -36,
      "rightShoulder.pitch": -36,
      "leftShoulder.spread": 0,
      "rightShoulder.spread": 0,
      "leftShoulder.twist": 80,
      "rightShoulder.twist": -80,
      "leftElbow.bend": 86,
      "rightElbow.bend": 86,
      "leftHand.roll": -35,
      "rightHand.roll": 35,
    },
  },
  {
    id: "lean",
    label: "倚靠",
    controls: {
      "body.roll": -10,
      "leftHip.spread": -8,
      "rightHip.spread": 8,
      "head.roll": 6,
    },
  },
  {
    id: "bow",
    label: "鞠躬",
    controls: {
      "body.pitch": -46,
      "torso.pitch": -10,
      "head.pitch": 20,
      "leftHip.pitch": 49,
      "rightHip.pitch": 49,
      "leftShoulder.pitch": 5,
      "rightShoulder.pitch": 5,
      "leftShoulder.spread": 10,
      "rightShoulder.spread": -10,
      "leftElbow.bend": 12,
      "rightElbow.bend": 12,
    },
  },
  {
    id: "think",
    label: "思考",
    controls: {
      "rightShoulder.pitch": 8,
      "rightShoulder.spread": 0,
      "rightShoulder.twist": -40,
      "rightElbow.bend": 90,
      "rightHand.roll": -40,
      "rightHand.pitch": 15,
      "rightHand.twist": -10,
      "leftShoulder.pitch": 8,
      "leftShoulder.spread": 0,
      "leftShoulder.twist": 40,
      "leftElbow.bend": 90,
    },
  },
  {
    id: "fight",
    label: "格斗",
    controls: {
      "body.yaw": -10,
      "body.pitch": 5,
      "torso.yaw": 8,
      "head.yaw": 8,
      "leftShoulder.pitch": 48,
      "leftShoulder.spread": -16,
      "leftShoulder.twist": 22,
      "rightShoulder.pitch": 30,
      "rightShoulder.spread": 0,
      "rightShoulder.twist": -22,
      "leftElbow.bend": 86,
      "rightElbow.bend": 84,
      "leftHip.spread": -18,
      "rightHip.spread": 22,
      "leftHip.pitch": 4,
      "rightHip.pitch": -6,
      "leftKnee.bend": 12,
      "rightKnee.bend": 18,
    },
  },
  {
    id: "kick",
    label: "踢球",
    controls: {
      "leftHip.pitch": -8,
      "rightHip.pitch": 58,
      "rightKnee.bend": 35,
      "leftShoulder.pitch": 18,
      "rightShoulder.pitch": -24,
    },
  },
  {
    id: "throw",
    label: "投掷",
    controls: {
      "body.offsetY": -0.12,
      "body.pitch": 5,
      "body.yaw": 14,
      "torso.yaw": -10,
      "head.yaw": 8,
      "rightShoulder.pitch": 76,
      "rightShoulder.spread": -14,
      "rightShoulder.twist": 28,
      "rightElbow.bend": 86,
      "rightHand.roll": 18,
      "rightHand.pitch": -12,
      "leftShoulder.pitch": 34,
      "leftShoulder.spread": 10,
      "leftShoulder.twist": 8,
      "leftElbow.bend": 54,
      "leftHand.pitch": -10,
      "leftHip.spread": -12,
      "rightHip.spread": 18,
      "leftHip.pitch": 24,
      "rightHip.pitch": -10,
      "leftKnee.bend": 30,
      "rightKnee.bend": 14,
      "leftFoot.pitch": -8,
      "rightFoot.roll": 6,
    },
  },
  {
    id: "push",
    label: "推进",
    controls: {
      "body.offsetY": -0.16,
      "body.pitch": 5,
      "body.yaw": 38,
      "torso.pitch": -4,
      "head.pitch": 6,
      "leftShoulder.pitch": 92,
      "rightShoulder.pitch": 92,
      "leftShoulder.spread": -11,
      "rightShoulder.spread": 11,
      "leftShoulder.twist": 6,
      "rightShoulder.twist": -6,
      "leftElbow.bend": 6,
      "rightElbow.bend": 6,
      "leftHand.pitch": -14,
      "rightHand.pitch": -14,
      "leftHip.spread": -12,
      "rightHip.spread": 14,
      "leftHip.pitch": 38,
      "rightHip.pitch": -20,
      "leftKnee.bend": 42,
      "rightKnee.bend": 20,
      "leftFoot.pitch": -6,
      "rightFoot.roll": 8,
    },
  },
  {
    id: "wave",
    label: "招手",
    controls: {
      "rightShoulder.pitch": 60,
      "rightShoulder.spread": 0,
      "rightShoulder.twist": 30,
      "rightElbow.bend": 90,
      "rightHand.roll": -20,
      "rightHand.pitch": 12,
      "rightHand.twist": 10,
      "leftShoulder.pitch": -10,
      "leftShoulder.spread": 8,
      "leftElbow.bend": 18,
      "leftHand.pitch": -8,
    },
  },
  {
    id: "reach",
    label: "伸手",
    controls: {
      "rightShoulder.pitch": 50,
      "rightElbow.bend": 12,
      "body.pitch": 0,
    },
  },
  {
    id: "cross-arms",
    label: "抱臂",
    controls: {
      "leftShoulder.pitch": 50,
      "leftShoulder.spread": -55,
      "leftShoulder.twist": 75,
      "leftElbow.bend": 50,
      "leftHand.roll": 0,
      "leftHand.pitch": -10,
      "rightShoulder.pitch": 90,
      "rightShoulder.spread": 55,
      "rightShoulder.twist": -45,
      "rightElbow.bend": 50,
      "rightHand.roll": 18,
      "rightHand.pitch": -10,
    },
  },
  {
    id: "phone",
    label: "看手机",
    controls: {
      "head.pitch": 18,
      "rightShoulder.pitch": 20,
      "rightShoulder.spread": -4,
      "rightShoulder.twist": -30,
      "rightElbow.bend": 82,
      "rightHand.roll": -30,
      "rightHand.pitch": 14,
      "rightHand.twist": 60,
      "leftShoulder.pitch": -10,
      "leftShoulder.spread": 8,
      "leftElbow.bend": 16,
      "leftHand.pitch": -8,
    },
  },
] as const;
