export const HUMANOID_CONTROL_KEYS = [
  "body.pitch",
  "body.yaw",
  "body.roll",
  "torso.pitch",
  "torso.yaw",
  "torso.roll",
  "head.pitch",
  "head.yaw",
  "head.roll",
  "leftShoulder.pitch",
  "leftShoulder.spread",
  "leftShoulder.twist",
  "rightShoulder.pitch",
  "rightShoulder.spread",
  "rightShoulder.twist",
  "leftElbow.bend",
  "rightElbow.bend",
  "leftHip.pitch",
  "leftHip.spread",
  "leftHip.twist",
  "rightHip.pitch",
  "rightHip.spread",
  "rightHip.twist",
  "leftKnee.bend",
  "rightKnee.bend",
] as const;
